### ISSUE TITLE
[request] alphabetic sorting considers alias

### ISSUE THREAD

**Issue by firinael** [Vinzent03/obsidian-sort-and-permute-lines#1]
Hi, just downloaded this to use in my notes index, but noticed that the plugin grabs the original name of the linked note instead of the alias being used.

Would it be possible to make it ignore the original name and sort based on the alias?

Thanks!

**Comment by Vinzent03** [comment]
Well I see your point and your use case, but I will have to figure out, how to get the aliases in a line.
