### ISSUE TITLE
Checkbox lists are not handled correctly

### ISSUE THREAD

**Issue by asitemade4u** [Vinzent03/obsidian-sort-and-permute-lines#10]
1. I have a list with checkboxes using the Markdown syntax: `- [ ]` and `- [x]`
2. Some are checked (`- [x]`)
3. When I sort the list, checkboxes are not taken into account, only the text acfter them, which is not logical IMO: the very purpose of me sorting the list was to isolate checked lines from unchecked ones (apart from the alphabetical sub-sort).

What I described is the way sorting works in VS Code.

**Comment by Vinzent03** [comment]
I see your point. Another user requested the exact opposite: #7 I understand both options and will add a setting for this.

**Comment by Vinzent03** [comment]
I added two new commands for this to support sorting the checkbox type too.
