### ISSUE TITLE
[Bug] in Sort Alhgorithm

### ISSUE THREAD

**Issue by L00tz1ffer** [Vinzent03/obsidian-sort-and-permute-lines#15]
# maybe unknown Bug in Sort Algorithm

I recently downloaded your Obsidian plugin in the need to sort some long lists with checkboxes (you got me those where shopping lists :D)

so i selected the whole list and pressed ctrl+p to sort the List alpabetically + checkboxes.

first it messed up my whole document, soine i did not know that i had to elect the specific list first lul

after that i ctrl-z tted everything and selected the list i wanted to have sorted.

**it sorted the list perfectly expect the items which contained a "Z" or "z" on its first letter**, those where placed everytime i wanted to sort the list - wrether or not having been checked on the end of the list, while every other item was sorted perfecly

but: good news!!
> this is the only bug i found so far ;)

Thank you anyways for creating such a useful plugin!!!

Best regrets

**Comment by Vinzent03** [comment]
Sorry, I can't reproduce any issues. Can you share an example text?

**Comment by L00tz1ffer** [comment]
thanx <3
