### ISSUE TITLE
[feature request] sort checkbox/task list by checked status

### ISSUE THREAD

**Issue by Helmoes** [Vinzent03/obsidian-sort-and-permute-lines#18]
Hi, would it be possible to implement a feature where a selected task list gets sorted so that the 'done' tasks are at the bottom? Something like this.  
![image](https://user-images.githubusercontent.com/61212162/198301441-ff4f6677-d93a-4081-bfa5-330df8eaa769.png)

**Comment by Vinzent03** [comment]
Should be possible via the command `Sort alphabetically with checkboxes'

**Comment by Helmoes** [comment]
That seems to work nicely for lists of the same indentation, thanks! I did try to sort a list with another indentation level as subtasks and that did mess up the order. If this is not the scope of the plugin I'll close the issue as not planned.  
![image](https://user-images.githubusercontent.com/61212162/198331238-1ee42066-3bea-47f0-b562-854e4ff56586.png)

**Comment by Vinzent03** [comment]
That's great, but then this is related to #16. I'll close this, because I would add support for checklist sorting in #16 as well.
