### ISSUE TITLE
dealing with indentations

### ISSUE THREAD

**Issue by jt196** [Vinzent03/obsidian-sort-and-permute-lines#21]
Great plugin, thanks for writing. 

I'm a bit of a list fan, and end up writing bulleted lists quite often. If they have indentations, the indented lines get sorted with the list, instead of separately. e.g.

```md
- item b
- item d
    - item a 
    - item e
- item c
```

Get sorted as

```md
    - item a
- item b
- item c
- item d
    - item e
```

instead of: 

```md
- item b
- item c
    - item e
- item d
    - item a
```

I think for most folks, an indentation is attached to the parent item, and would mean to skip the sorting of the parent, but possibly sort within that particular level.

**Comment by josephdong1000** [comment]
I made a similar request several months ago #16! The feature was just recently added -- try `Sort current list recursively`

**Comment by jt196** [comment]
Nice one dude, I hadn't updated the plugin! Tried all the options, so guess someone was ahead of me!
