### ISSUE TITLE
Feature request: add command to sort by checkboxes only

### ISSUE THREAD

**Issue by YousufSSyed** [Vinzent03/obsidian-sort-and-permute-lines#24]
I mainly use the "sort current list alphabetically with checkboxes" command to sort checkbox lists by if they're checked or not. A command just for checkboxes would be very helpful.

**Comment by Vinzent03** [comment]
What do you mean with
> A command just for checkboxes

**Comment by YousufSSyed** [comment]
Sort the list so that unchecked items are on top and checked ones are on the bottoms, use no other criteria for sorting.

**Comment by Vinzent03** [comment]
A new command sort by checkboxes is now available!

**Comment by YousufSSyed** [comment]
@Vinzent03 I updated the plugin and checked that it's version 0.7.0, however it's not working for me.

https://user-images.githubusercontent.com/42646062/217362553-3de90ce4-b161-45c8-807a-3b14144945d6.mov

By the way, did you make it so that it works recursively too? And keeps the order (besides moving checked and unchecked items)?

**Comment by Vinzent03** [comment]
May you something write something into the line between your two lists, below "Edit CSS files". Obsidian detects them as one loose list.
> did you make it so that it works recursively too? And keeps the order (besides moving checked and unchecked items)?

I did

**Comment by YousufSSyed** [comment]
Nothing happened still. However, "sort list alphabetically by checkboxes" works on that list.

https://user-images.githubusercontent.com/42646062/217504060-3b52c180-eb49-4cd8-9c0d-e0c0994e8022.mov

**Comment by Vinzent03** [comment]
Can reproduce that case. Please try with an empty line above "Stuff". Obsidian still tracks it as one list.

**Comment by YousufSSyed** [comment]
When I create a new line about "Stuff" and then sort it, it sorts the whole page, which I _don't_ want. How come I can select a list and sort alphabetically by checkboxes (and only change that one list like I intend it to), but it doesn't work to sort by just checkboxes?

**Comment by YousufSSyed** [comment]
@Vinzent03 I notice that when I have two lists separated by blank lines and and I run "sort current list alphabetically" with my caret on the 1st one, it will sort both lists as one when I want to just sort the 1st list. You said in your other reply _"Obsidian still tracks it as one list."_ Would that be the case here? Do I have to write text in between the two lists so they don't combine, or can you make it so that only the selected list gets sorted?

**Comment by Vinzent03** [comment]
@YousufSSyed 
> You said in your other reply "Obsidian still tracks it as one list." Would that be the case here? Do I have to write text in between the two lists so they don't combine [...]

That is correct.

**Comment by YousufSSyed** [comment]
Can you make it so it doesn't, and without having to write text above or below the list?

**Comment by Vinzent03** [comment]
I currently don't plan to do so, because I wouldn't be able to use the metadata cache Obsidian provides. Resulting in a more complicated implementation.

**Comment by YousufSSyed** [comment]
Alright. I've been thinking about getting into plugin development eventually, idk it would be possible to do this.
