### ISSUE TITLE
Issue: "Sort Current List Alphabetically" also moves sub bullet points either outside of the list or under different 

### ISSUE THREAD

**Issue by YousufSSyed** [Vinzent03/obsidian-sort-and-permute-lines#25]
https://user-images.githubusercontent.com/42646062/217658478-119439da-2aa1-48ec-a1fc-09760c0f984a.mov

Sub bullet points should be left under the same parent bullets. 
Also, you should make a separate command to sort alphabetically and recursively, where sub bullet points are sorted alphabetically but stay under the same bullet point.

**Comment by fccfc5d245c** [comment]
I came here to post the same issue. / enhancement. Nearly all my lists have sub-bullet points, so this plugin went from miracle to unusable on the second test.
So +1 except for this:

> Also, you should make a separate command to sort alphabetically and recursively, where sub bullet points are sorted alphabetically but stay under the same bullet point.

In my case, I don't order sub bullet points alphabetically, so I don't request that feature. But it wouldn't hurt to have the option.

Thanks to the dev anyway, for simple lists, it is Perfect

**Comment by Vinzent03** [comment]
@YousufSSyed Please use the command "Sort current list recursively"

**Comment by YousufSSyed** [comment]
This seems to be fixed.
