### ISSUE TITLE
Sorting bug

### ISSUE THREAD

**Issue by scottTomaszewski** [Vinzent03/obsidian-sort-and-permute-lines#3]
There seems to be a bug when sorting.  Haven't tracked down the exact issue, but when I have a list item link above the lines to sort, the sort result is wrong.  See gif, notice the `0` is between the `f` and `g` :
![obsidian sorting doesnt work](https://user-images.githubusercontent.com/5295276/120926652-cadb2980-c6ab-11eb-96b1-47b1442ff3d8.gif)

Obsidian version 0.12.3
Sort and Permute lines version 0.1.1

**Comment by Vinzent03** [comment]
Thanks for the issue. I could fix it. Please update to 0.1.2

**Comment by scottTomaszewski** [comment]
Thanks!
