### ISSUE TITLE
Sort list bug, final line is not truncated properly

### ISSUE THREAD

**Issue by luckman212** [Vinzent03/obsidian-sort-and-permute-lines#9]
Found a strange bug, with the sort list function. Obsidian 0.13.6 / plugin ver 0.3.0

It depends on where the cursor is when you trigger the sort, so I am guessing it's related to the function below, but I can't quite wrap my head around where the bug is. https://github.com/Vinzent03/obsidian-sort-and-permute-lines/blob/401e4c8a68d4b29dd5f9c4ea4835c22f49f660fe/main.ts#L133

Example, try sorting this list with the cursor at the `|` position:
```
- [ ] beta
- [x] acme
- [x] warren
- [ ] zelda
- [x] simon & garfunkel|
- [ ] davidoff
```

(hint: It works fine)

BUT, if you position the cursor here:
```
- [ ] beta|
- [x] acme
- [x] warren
- [ ] zelda
- [x] simon & garfunkel
- [ ] davidoff
```
and sort...
```
- [x] acme
- [ ] beta
- [ ] davidoff
- [x] simon & garfunkel
- [x] warren
- [ ] zeldadoff
```
(note the extra `doff` chars at the final line)

**Comment by Vinzent03** [comment]
Can reproduce by using the sort list alphabetically command.

**Comment by luckman212** [comment]
Wow, wasn't expecting such a quick fix, thank you @Vinzent03 !! Confirmed the fix is working great. 🚀

**Comment by Vinzent03** [comment]
Was an easy fix just before my dinner 😅. Happy to help.
